[project]
name = "acquirium-backend"
version = "0.1.0"
description = "FastAPI backend for Acquirium GUI"
readme = "README.md"
requires-python = ">=3.12"

authors = [
    { name = "Lucas Hoke", email = "lhoke@mines.edu" },
    { name = "Ari Derritt", email = "arijaye_derritt@mines.edu" },
    { name = "Liam O'Byrne", email = "liam_obyrne@mines.edu" },
    { name = "Victoria Potts", email = "vpotts@mines.edu" }
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Framework :: FastAPI",
    "License :: MIT License",
]

# Track your primary open-source dependencies directly inside the TOML
dependencies = [
    "fastapi>=0.141.1",
]

[project.optional-dependencies]
# Dependencies specifically for open-source contributors/testing
dev = [
    "pytest>=9.1.1"
]